swagger: '2.0'
info:
  version: '1.0'
  title: Banka
  description: >-
    Banka is a light-weight core banking application that powers banking operations like account

    creation, customer deposit and withdrawals. This app is meant to support a single bank, where

    users can signup and create bank accounts online, but must visit the branch to withdraw or

    deposit money..
  contact: {}
host: banka--app.herokuapp.com
basePath: /api/v2
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /user/{email}/accounts:
    get:
      description: GET /user/<user-email-address>/accounts
      summary: View all accounts owned by a specific user (client) .
      tags:
      - User
      operationId: UserAccountsByEmailGet
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: email
        in: path
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Adminorstaffcanviewallaccountsownedbyaspecificuser%28client%29.'
          headers:
            connection:
              type: string
              default: keep-alive
            content-length:
              type: string
              default: 2172
            content-type:
              type: string
              default: application/json; charset=utf-8
            date:
              type: string
              default: Sun, 28 Apr 2019 18:37:03 GMT
            etag:
              type: string
              default: W/"87c-ncH7icM+9XRkvwX36PjowMB9Okg"
            server:
              type: string
              default: Cowboy
            via:
              type: string
              default: 1.1 vegur
            x-powered-by:
              type: string
              default: Express
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/Clienttriestodebitanaccount'
          examples:
            application/json:
              status: 404
              error: Email does not exist
  /transactions/{accountNo}/debit:
    post:
      description: POST /transactions/<account-number>/debit
      summary: Debit a bank account
      tags:
      - Transactions
      operationId: TransactionsDebitByAccountNoPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: accountNo
        in: path
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/DebitabankaccountRequest'
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Clienttriestodebitanaccount'
          examples:
            application/json:
              status: 401
              error: You do not have the rights to this resource
          headers:
            connection:
              type: string
              default: keep-alive
            content-length:
              type: string
              default: 68
            content-type:
              type: string
              default: application/json; charset=utf-8
            date:
              type: string
              default: Sun, 28 Apr 2019 18:47:54 GMT
            etag:
              type: string
              default: W/"44-qVp6hDINKr5/jvT+n6X/xN9+QZE"
            server:
              type: string
              default: Cowboy
            via:
              type: string
              default: 1.1 vegur
            x-powered-by:
              type: string
              default: Express
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Clienttriestodebitanaccount'
          examples:
            application/json:
              status: 400
              error: Please put in a number to deposit or withdraw
  /transactions/{accountNo}/credit:
    post:
      description: POST /transactions/<account-number>/credit
      summary: Credit a bank account
      tags:
      - Transactions
      operationId: TransactionsCreditByAccountNoPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: accountNo
        in: path
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Clienttriestodoacredittransaction'
          examples:
            application/json:
              status: 401
              error: You do not have the rights to this resource
          headers:
            connection:
              type: string
              default: keep-alive
            content-length:
              type: string
              default: 68
            content-type:
              type: string
              default: application/json; charset=utf-8
            date:
              type: string
              default: Sun, 28 Apr 2019 18:57:14 GMT
            etag:
              type: string
              default: W/"44-qVp6hDINKr5/jvT+n6X/xN9+QZE"
            server:
              type: string
              default: Cowboy
            via:
              type: string
              default: 1.1 vegur
            x-powered-by:
              type: string
              default: Express
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Clienttriestodebitanaccount'
          examples:
            application/json:
              status: 400
              error: Invalid input, try again
  /transactions/{id}:
    get:
      description: GET /transactions/<transaction-id>
      summary: View a specific transaction .
      tags:
      - Transactions
      operationId: TransactionsByIdGet
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Usertriestoviewaspecifictransaction'
          examples:
            application/json:
              status: 200
              data:
                transactionId: 20
                createdOn: 2019-04-22T20:02:37.278Z
                type: debit
                accountNumber: 20000006
                amount: 2500.5
                oldBalance: 22505.09
                newBalance: 20004.59
          headers:
            connection:
              type: string
              default: keep-alive
            content-length:
              type: string
              default: 181
            content-type:
              type: string
              default: application/json; charset=utf-8
            date:
              type: string
              default: Sun, 28 Apr 2019 18:59:56 GMT
            etag:
              type: string
              default: W/"b5-xpqAkx9904rOKVAWbL7jmnlZVz0"
            server:
              type: string
              default: Cowboy
            via:
              type: string
              default: 1.1 vegur
            x-powered-by:
              type: string
              default: Express
  /accounts:
    post:
      description: POST /accounts
      summary: Create a bank account
      tags:
      - Accounts
      operationId: AccountsPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/CreateabankaccountRequest'
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Createabankaccount'
          examples:
            application/json:
              status: 200
              data:
                accountNumber: 20000060
                firstName: oghenefegor
                lastName: iyara
                email: fegzycolezya@gmail.com
                type: savings
                openingBalance: 0
          headers:
            connection:
              type: string
              default: keep-alive
            content-length:
              type: string
              default: 162
            content-type:
              type: string
              default: application/json; charset=utf-8
            date:
              type: string
              default: Sun, 28 Apr 2019 17:59:45 GMT
            etag:
              type: string
              default: W/"a2-mnb3gi9+VrpkBs92L8msCYgXJy0"
            server:
              type: string
              default: Cowboy
            via:
              type: string
              default: 1.1 vegur
            x-powered-by:
              type: string
              default: Express
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Clienttriestodebitanaccount'
          examples:
            application/json:
              status: 400
              error: This field is required, Account type can only be savings or current
    get:
      description: GET /accounts
      summary: View a list of all bank accounts .
      tags:
      - Accounts
      operationId: AccountsGet
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Viewalistofallbankaccounts.'
          headers:
            connection:
              type: string
              default: keep-alive
            content-length:
              type: string
              default: 5613
            content-type:
              type: string
              default: application/json; charset=utf-8
            date:
              type: string
              default: Sun, 28 Apr 2019 18:23:02 GMT
            etag:
              type: string
              default: W/"15ed-8tc2x3PPNsTbnAX++B6FnkXwmOw"
            server:
              type: string
              default: Cowboy
            via:
              type: string
              default: 1.1 vegur
            x-powered-by:
              type: string
              default: Express
  /accounts/{accountNo}:
    patch:
      description: PATCH /account/<account-number>
      summary: Change account status
      tags:
      - Accounts
      operationId: AccountsByAccountNoPatch
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: accountNo
        in: path
        required: true
        type: string
        description: ''
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: status
        in: formData
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Changeaccountstatussuccessfully'
          examples:
            application/json:
              status: 200
              data:
                accountNo: 20000005
                status: active
          headers:
            connection:
              type: string
              default: keep-alive
            content-length:
              type: string
              default: 62
            content-type:
              type: string
              default: application/json; charset=utf-8
            date:
              type: string
              default: Sun, 28 Apr 2019 18:05:03 GMT
            etag:
              type: string
              default: W/"3e-4LgHLHLTnxa7vc3Q+oPY4Bg/7ps"
            server:
              type: string
              default: Cowboy
            via:
              type: string
              default: 1.1 vegur
            x-powered-by:
              type: string
              default: Express
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Deleteanaccountnumbersuccessfully'
          examples:
            application/json:
              status: 400
              message: Status can only be active or dormant
    delete:
      description: DELETE /accounts/<account-number>
      summary: Delete an account number
      tags:
      - Accounts
      operationId: AccountsByAccountNoDelete
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: accountNo
        in: path
        required: true
        type: string
        description: ''
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          type: object
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Deleteanaccountnumbersuccessfully'
          examples:
            application/json:
              status: 200
              message: Account deleted successfully
          headers:
            connection:
              type: string
              default: keep-alive
            content-length:
              type: string
              default: 55
            content-type:
              type: string
              default: application/json; charset=utf-8
            date:
              type: string
              default: Sun, 28 Apr 2019 18:09:06 GMT
            etag:
              type: string
              default: W/"37-7DD8oNpDeo95pZzjkv2S3PdRdnM"
            server:
              type: string
              default: Cowboy
            via:
              type: string
              default: 1.1 vegur
            x-powered-by:
              type: string
              default: Express
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/Clienttriestodebitanaccount'
          examples:
            application/json:
              status: 404
              error: Account Not Found
    get:
      description: GET /accounts/<account-number>
      summary: View a specific account’s details .
      tags:
      - Accounts
      operationId: AccountsByAccountNoGet
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: accountNo
        in: path
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Viewaspecificaccount%E2%80%99sdetails.'
          examples:
            application/json:
              status: 200
              data:
                createdOn: 2019-04-22T12:35:25.5Z
                accountNumber: 20000005
                ownerEmail: fereoomee@gmail.com
                type: savings
                status: active
                balance: 10002.74
          headers:
            connection:
              type: string
              default: keep-alive
            content-length:
              type: string
              default: 176
            content-type:
              type: string
              default: application/json; charset=utf-8
            date:
              type: string
              default: Sun, 28 Apr 2019 18:11:16 GMT
            etag:
              type: string
              default: W/"b0-vLf4aL1UGiYI+irTxlmzcRqbUsU"
            server:
              type: string
              default: Cowboy
            via:
              type: string
              default: 1.1 vegur
            x-powered-by:
              type: string
              default: Express
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/Clienttriestodebitanaccount'
          examples:
            application/json:
              status: 404
              error: Account Not Found
  /accounts/{accountNo}/transactions:
    get:
      description: GET /accounts/<account-number>/transactions
      summary: View an account’s transaction history .
      tags:
      - Accounts
      operationId: AccountsTransactionsByAccountNoGet
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: accountNo
        in: path
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Viewanaccount%E2%80%99stransactionhistorysuccessfully'
          headers:
            access-control-allow-headers:
              type: string
              default: X-Requested-With
            access-control-allow-origin:
              type: string
              default: '*'
            connection:
              type: string
              default: keep-alive
            content-length:
              type: string
              default: 42381
            content-type:
              type: string
              default: application/json; charset=utf-8
            date:
              type: string
              default: Sun, 28 Apr 2019 18:15:59 GMT
            etag:
              type: string
              default: W/"a58d-tmCesdqV3i6vKMBWN0hBDVeVjAE"
            x-powered-by:
              type: string
              default: Express
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/Clienttriestodebitanaccount'
          examples:
            application/json:
              status: 404
              error: Account Not Found
  /auth/signup:
    post:
      description: POST /auth/signup
      summary: Register a new user
      tags:
      - Auth
      operationId: AuthSignupPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/RegisteranewuserRequest'
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/SIgnupnewuser'
          examples:
            application/json:
              status: 201
              data:
                id: 35
                firstname: oghenefegor
                lastname: iyara
                email: ferguiosmnssmsbsnljjkvsoniyara@gmail.com
                type: cashier
                isadmin: false
                token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozNSwiZW1haWwiOiJmZXJndWlvc21uc3Ntc2Jzbmxqamt2c29uaXlhcmFAZ21haWwuY29tIiwiZmlyc3RuYW1lIjoib2doZW5lZmVnb3IiLCJsYXN0bmFtZSI6Iml5YXJhIiwicGFzc3dvcmQiOiIkMmEkMTAkbUFnUG5vaUF0ODU3ZzZXQW9aTDlTLi9ZeFJLbXZIUFZ5bGFCQUkwbnZaa1MuQndvYnp1RkciLCJ0eXBlIjoiY2FzaGllciIsImlzYWRtaW4iOmZhbHNlfSwiaWF0IjoxNTU2Mzc4ODczLCJleHAiOjE1NTY0NjUyNzN9.J0yMidMq7k9HxTPR7c_PRlMoqZvDI_rfui1ULI-IFS4
          headers:
            connection:
              type: string
              default: keep-alive
            content-length:
              type: string
              default: 592
            content-type:
              type: string
              default: application/json; charset=utf-8
            date:
              type: string
              default: Sat, 27 Apr 2019 15:27:53 GMT
            etag:
              type: string
              default: W/"250-oHIGRIk4DXcPQfMeYcbvIgzlFRQ"
            server:
              type: string
              default: Cowboy
            via:
              type: string
              default: 1.1 vegur
            x-powered-by:
              type: string
              default: Express
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Clienttriestodebitanaccount'
          examples:
            application/json:
              status: 400
              error: Password should be at least 4 characters without any whitespace(s)
        409:
          description: Conflict
          schema:
            $ref: '#/definitions/Clienttriestodebitanaccount'
          examples:
            application/json:
              status: 409
              error: Email Already Exists
  /auth/signin:
    post:
      description: POST /auth/signin
      summary: Log in a user
      tags:
      - Auth
      operationId: AuthSigninPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/LoginauserRequest'
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Signusersuccessfully'
          examples:
            application/json:
              status: 200
              data:
                token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozMCwiZW1haWwiOiJmZXJndXNvbml5YXJhYUBnbWFpbC5jb20iLCJmaXJzdG5hbWUiOiJmZXJndXNvbiIsImxhc3RuYW1lIjoiaXlhcmEgIiwicGFzc3dvcmQiOiIkMmEkMTAkc2pHU1VYR2NqeWdhcGhSeGhBcmJLZWhsR2Uzenh1WHNEUXZLQUJFLkVWY05JTC5FLzhCeHkiLCJ0eXBlIjoiY2xpZW50IiwiaXNhZG1pbiI6ZmFsc2V9LCJpYXQiOjE1NTYzNzk2NjEsImV4cCI6MTU1NjQ2NjA2MX0.O-tEvQaAxhHJi9D634WbCJ-9kXPyKixMWOrMw0JMBj8
                id: 30
                firstName: ferguson
                lastName: 'iyara '
                email: fergusoniyaraa@gmail.com
          headers:
            connection:
              type: string
              default: keep-alive
            content-length:
              type: string
              default: 516
            content-type:
              type: string
              default: application/json; charset=utf-8
            date:
              type: string
              default: Sat, 27 Apr 2019 15:41:00 GMT
            etag:
              type: string
              default: W/"204-bErS0s0BjY+fTXzzMx/y3osWf+A"
            server:
              type: string
              default: Cowboy
            via:
              type: string
              default: 1.1 vegur
            x-powered-by:
              type: string
              default: Express
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Clienttriestodebitanaccount'
          examples:
            application/json:
              status: 400
              error: Your email is required, example fergusoniyara@banka.com
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/Clienttriestodebitanaccount'
          examples:
            application/json:
              status: 404
              error: Email does not exist
definitions:
  Adminorstaffcanviewallaccountsownedbyaspecificuser(client).:
    title: Adminorstaffcanviewallaccountsownedbyaspecificuser(client).
    type: object
    properties:
      status:
        type: integer
        format: int32
      accounts:
        type: array
        items:
          $ref: '#/definitions/Account'
    required:
    - status
    - accounts
  Account:
    title: Account
    type: object
    properties:
      createdon:
        example: 2019-04-22T12:35:15.481Z
        type: string
      accountnumber:
        example: 20000003
        type: integer
        format: int32
      type:
        example: savings
        type: string
      status:
        example: draft
        type: string
      balance:
        example: 0
        type: integer
        format: int32
    required:
    - createdon
    - accountnumber
    - type
    - status
    - balance
  DebitabankaccountRequest:
    title: DebitabankaccountRequest
    example:
      type: debit
      amountToDeposit: 2500.56005
    type: object
    properties:
      type:
        type: string
      amountToDeposit:
        type: number
        format: double
    required:
    - type
    - amountToDeposit
  Clienttriestodebitanaccount:
    title: Clienttriestodebitanaccount
    example:
      status: 401
      error: You do not have the rights to this resource
    type: object
    properties:
      status:
        type: integer
        format: int32
      error:
        type: string
    required:
    - status
    - error
  Clienttriestodoacredittransaction:
    title: Clienttriestodoacredittransaction
    example:
      status: 401
      error: You do not have the rights to this resource
    type: object
    properties:
      status:
        type: integer
        format: int32
      error:
        type: string
    required:
    - status
    - error
  Usertriestoviewaspecifictransaction:
    title: Usertriestoviewaspecifictransaction
    example:
      status: 200
      data:
        transactionId: 20
        createdOn: 2019-04-22T20:02:37.278Z
        type: debit
        accountNumber: 20000006
        amount: 2500.5
        oldBalance: 22505.09
        newBalance: 20004.59
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        $ref: '#/definitions/Data'
    required:
    - status
    - data
  Data:
    title: Data
    type: object
    properties:
      transactionId:
        type: integer
        format: int32
      createdOn:
        type: string
      type:
        type: string
      accountNumber:
        type: integer
        format: int32
      amount:
        type: number
        format: double
      oldBalance:
        type: number
        format: double
      newBalance:
        type: number
        format: double
    required:
    - transactionId
    - createdOn
    - type
    - accountNumber
    - amount
    - oldBalance
    - newBalance
  CreateabankaccountRequest:
    title: CreateabankaccountRequest
    example:
      type: savings
    type: object
    properties:
      type:
        type: string
    required:
    - type
  Createabankaccount:
    title: Createabankaccount
    example:
      status: 200
      data:
        accountNumber: 20000060
        firstName: oghenefegor
        lastName: iyara
        email: fegzycolezya@gmail.com
        type: savings
        openingBalance: 0
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        $ref: '#/definitions/Data1'
    required:
    - status
    - data
  Data1:
    title: Data1
    type: object
    properties:
      accountNumber:
        type: integer
        format: int32
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      type:
        type: string
      openingBalance:
        type: integer
        format: int32
    required:
    - accountNumber
    - firstName
    - lastName
    - email
    - type
    - openingBalance
  Viewalistofallbankaccounts.:
    title: Viewalistofallbankaccounts.
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        type: array
        items:
          $ref: '#/definitions/Data2'
    required:
    - status
    - data
  Data2:
    title: Data2
    type: object
    properties:
      createdon:
        example: 2019-04-22T12:35:15.481Z
        type: string
      accountnumber:
        example: 20000003
        type: integer
        format: int32
      email:
        example: fereoomee@gmail.com
        type: string
      type:
        example: savings
        type: string
      status:
        example: draft
        type: string
      balance:
        example: 0
        type: integer
        format: int32
    required:
    - createdon
    - accountnumber
    - email
    - type
    - status
    - balance
  Changeaccountstatussuccessfully:
    title: Changeaccountstatussuccessfully
    example:
      status: 200
      data:
        accountNo: 20000005
        status: active
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        $ref: '#/definitions/Data3'
    required:
    - status
    - data
  Data3:
    title: Data3
    type: object
    properties:
      accountNo:
        type: integer
        format: int32
      status:
        type: string
    required:
    - accountNo
    - status
  Deleteanaccountnumbersuccessfully:
    title: Deleteanaccountnumbersuccessfully
    example:
      status: 200
      message: Account deleted successfully
    type: object
    properties:
      status:
        type: integer
        format: int32
      message:
        type: string
    required:
    - status
    - message
  Viewaspecificaccount’sdetails.:
    title: Viewaspecificaccount’sdetails.
    example:
      status: 200
      data:
        createdOn: 2019-04-22T12:35:25.5Z
        accountNumber: 20000005
        ownerEmail: fereoomee@gmail.com
        type: savings
        status: active
        balance: 10002.74
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        $ref: '#/definitions/Data4'
    required:
    - status
    - data
  Data4:
    title: Data4
    type: object
    properties:
      createdOn:
        type: string
      accountNumber:
        type: integer
        format: int32
      ownerEmail:
        type: string
      type:
        type: string
      status:
        type: string
      balance:
        type: number
        format: double
    required:
    - createdOn
    - accountNumber
    - ownerEmail
    - type
    - status
    - balance
  Viewanaccount’stransactionhistorysuccessfully:
    title: Viewanaccount’stransactionhistorysuccessfully
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        type: array
        items:
          $ref: '#/definitions/Data5'
    required:
    - status
    - data
  Data5:
    title: Data5
    type: object
    properties:
      id:
        example: 7
        type: integer
        format: int32
      createdon:
        example: 2019-04-21T23:00:00Z
        type: string
      type:
        example: credit
        type: string
      accountnumber:
        example: 20000005
        type: integer
        format: int32
      amount:
        example: 2500
        type: integer
        format: int32
      oldbalance:
        example: 0
        type: integer
        format: int32
      newbalance:
        example: 2500
        type: integer
        format: int32
    required:
    - id
    - createdon
    - type
    - accountnumber
    - amount
    - oldbalance
    - newbalance
  Viewalistofallactivebankaccounts.:
    title: Viewalistofallactivebankaccounts.
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        type: array
        items:
          $ref: '#/definitions/Data6'
    required:
    - status
    - data
  Data6:
    title: Data6
    type: object
    properties:
      createdon:
        example: 2019-04-22T12:35:25.5Z
        type: string
      accountnumber:
        example: 20000005
        type: integer
        format: int32
      email:
        example: fereoomee@gmail.com
        type: string
      type:
        example: savings
        type: string
      status:
        example: active
        type: string
      balance:
        example: 10002.73985
        type: number
        format: double
    required:
    - createdon
    - accountnumber
    - email
    - type
    - status
    - balance
  Viewalistofalldormantbankaccounts.:
    title: Viewalistofalldormantbankaccounts.
    example:
      status: 200
      data:
      - createdon: 2019-04-22T12:35:25.5Z
        accountnumber: 20000005
        email: fereoomee@gmail.com
        type: savings
        status: dormant
        balance: 10002.73985
      - createdon: 2019-04-25T21:43:43.624Z
        accountnumber: 20000050
        email: figoryo@gmail.com
        type: savings
        status: dormant
        balance: 0
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        type: array
        items:
          $ref: '#/definitions/Data6'
    required:
    - status
    - data
  RegisteranewuserRequest:
    title: RegisteranewuserRequest
    example:
      firstName: oghenefegor
      lastName: iyara
      email: ferguiosmnssmsbsvsoniyara@gmail.com
      password: fegzycolezy
      type: cashier
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      type:
        type: string
    required:
    - firstName
    - lastName
    - email
    - password
    - type
  SIgnupnewuser:
    title: SIgnupnewuser
    example:
      status: 201
      data:
        id: 35
        firstname: oghenefegor
        lastname: iyara
        email: ferguiosmnssmsbsnljjkvsoniyara@gmail.com
        type: cashier
        isadmin: false
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozNSwiZW1haWwiOiJmZXJndWlvc21uc3Ntc2Jzbmxqamt2c29uaXlhcmFAZ21haWwuY29tIiwiZmlyc3RuYW1lIjoib2doZW5lZmVnb3IiLCJsYXN0bmFtZSI6Iml5YXJhIiwicGFzc3dvcmQiOiIkMmEkMTAkbUFnUG5vaUF0ODU3ZzZXQW9aTDlTLi9ZeFJLbXZIUFZ5bGFCQUkwbnZaa1MuQndvYnp1RkciLCJ0eXBlIjoiY2FzaGllciIsImlzYWRtaW4iOmZhbHNlfSwiaWF0IjoxNTU2Mzc4ODczLCJleHAiOjE1NTY0NjUyNzN9.J0yMidMq7k9HxTPR7c_PRlMoqZvDI_rfui1ULI-IFS4
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        $ref: '#/definitions/Data8'
    required:
    - status
    - data
  Data8:
    title: Data8
    type: object
    properties:
      id:
        type: integer
        format: int32
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string
      type:
        type: string
      isadmin:
        type: boolean
      token:
        type: string
    required:
    - id
    - firstname
    - lastname
    - email
    - type
    - isadmin
    - token
  LoginauserRequest:
    title: LoginauserRequest
    example:
      email: fergusoniyaraa@gmail.com
      password: somepassword1
    type: object
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
  Signusersuccessfully:
    title: Signusersuccessfully
    example:
      status: 200
      data:
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozMCwiZW1haWwiOiJmZXJndXNvbml5YXJhYUBnbWFpbC5jb20iLCJmaXJzdG5hbWUiOiJmZXJndXNvbiIsImxhc3RuYW1lIjoiaXlhcmEgIiwicGFzc3dvcmQiOiIkMmEkMTAkc2pHU1VYR2NqeWdhcGhSeGhBcmJLZWhsR2Uzenh1WHNEUXZLQUJFLkVWY05JTC5FLzhCeHkiLCJ0eXBlIjoiY2xpZW50IiwiaXNhZG1pbiI6ZmFsc2V9LCJpYXQiOjE1NTYzNzk2NjEsImV4cCI6MTU1NjQ2NjA2MX0.O-tEvQaAxhHJi9D634WbCJ-9kXPyKixMWOrMw0JMBj8
        id: 30
        firstName: ferguson
        lastName: 'iyara '
        email: fergusoniyaraa@gmail.com
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        $ref: '#/definitions/Data9'
    required:
    - status
    - data
  Data9:
    title: Data9
    type: object
    properties:
      token:
        type: string
      id:
        type: integer
        format: int32
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
    required:
    - token
    - id
    - firstName
    - lastName
    - email
tags:
- name: User
  description: api/v2/user/<user-email>/accounts
- name: Transactions
- name: Accounts
  description: Accounts related endpoints
- name: Auth
  description: Endpoints for signup and signin
